"""add seed data for borrowers and books

Revision ID: 26fb0704ee86
Revises: c0fc48ed0529
Create Date: 2025-06-03 21:06:09.747692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fb0704ee86'
down_revision: Union[str, None] = 'c0fc48ed0529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
