"""add seed data for borrowers and books

Revision ID: 89b4cce66c82
Revises: 26fb0704ee86
Create Date: 2025-06-03 21:07:27.107759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b4cce66c82'
down_revision: Union[str, None] = '26fb0704ee86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
