"""add seed data for 2025 borrowers and books

Revision ID: c92bd4edfcfa
Revises: b2cb17e00243
Create Date: 2025-06-03 21:59:42.920475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92bd4edfcfa'
down_revision: Union[str, None] = 'b2cb17e00243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
